version: "2"

services:
  journal_io:
    image: tcardoso2/journal.io:latest
    ports:
      - 8084:8084
      - 8069:8068
    container_name: journal.io
    #restart: always
    environment:
      - LOG_SOCKET_PORT=8068
      - LOG_LEVEL=trace
      - API_PORT=8084
    volumes:
      - ./logs:/home/node/journal.io/logs
      - ./bin:/home/node/journal.io/bin
      - ~/work/docker/oznu_homebridge/homebridge/homebridge.log:/home/node/journal.io/target
